annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/kube-version: '>= 1.16.0-0'
  catalog.cattle.io/rancher-version: '>= 2.10.0-0'
  catalog.cattle.io/ui-extensions-version: '>= 3.0.0 < 4.0.0'
  catalog.cattle.io/ui-version: '>= 2.7.2'
apiVersion: v2
appVersion: 3.0.2-rc.1
description: OS Management extension
name: elemental
type: application
version: 3.0.2-rc.1
icon: >-
  https://raw.githubusercontent.com/rancher/elemental-ui/main/pkg/elemental/icon-v2.svg
